services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NEXT_PUBLIC_SERVICE_API_URL=${NEXT_PUBLIC_SERVICE_API_URL}
        - NEXT_PUBLIC_EMAIL_DOMAIN=${NEXT_PUBLIC_EMAIL_DOMAIN}
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - host.docker.internal:host-gateway
